### ISSUE TITLE
[Bug]: failed to load 'cc/spreadsheetimporter/v0_31_1/Component.js'

### ISSUE THREAD

**Issue by andresj6** [marianfoo/ui5-cc-spreadsheetimporter#466]
### OData Version

OData V4

### Draft

Yes

### Scenario

Fiori Elements

### UI5 Spreadsheet Component

v0_31_1

### What happened?

Hi Marian, I get an error loading the component. I have seen in the documentation the troubleshooting of this error but in my case the version of the component in the dependencies of package.json and manifest.json matches.
- Error:
![image](https://github.com/marianfoo/ui5-cc-spreadsheetimporter/assets/61234688/e2401729-8759-4bfe-8d03-b0c711409b3d)
- package.json:
![image](https://github.com/marianfoo/ui5-cc-spreadsheetimporter/assets/61234688/d9cb566a-4a90-4485-a7e3-8a946c00fc13)
- manifest.json:
![image](https://github.com/marianfoo/ui5-cc-spreadsheetimporter/assets/61234688/b7f0d059-b9b8-4ae6-a472-8cc6384e34a4)

¿What is the problem then?
Thanks.

### Relevant log output

```shell
ui5loader-dbg.js:1190 Uncaught (in promise) ModuleError: failed to load 'cc/spreadsheetimporter/v0_31_1/Component.js' from sap/bc/ui5_ui5/sap/z_fintranflwtyp/~52363F9C219D8350068C979FF1096A49~5/thirdparty/customControl/spreadsheetImporter/v0_31_1/Component.js: 404
    at ye (https://ui5.sap.com/1.114.11/resources/sap/ushell_abap/bootstrap/evo/abap.js:9:7867)
    at pe.failWith (https://ui5.sap.com/1.114.11/resources/sap/ushell_abap/bootstrap/evo/abap.js:9:5704)
    at Ie (https://ui5.sap.com/1.114.11/resources/sap/ushell_abap/bootstrap/evo/abap.js:9:14487)
    at Me (https://ui5.sap.com/1.114.11/resources/sap/ushell_abap/bootstrap/evo/abap.js:9:16457)
    at Object.r [as require] (https://ui5.sap.com/1.114.11/resources/sap/ushell_abap/bootstrap/evo/abap.js:9:19823)
    at https://ui5.sap.com/1.114.11/resources/sap/ushell_abap/bootstrap/evo/core-min-1.js:598:34696
    at new Promise (<anonymous>)
    at https://ui5.sap.com/1.114.11/resources/sap/ushell_abap/bootstrap/evo/core-min-1.js:598:34663
Caused by: XHRLoadError: 404
    at n (https://ui5.sap.com/1.114.11/resources/sap/ushell_abap/bootstrap/evo/abap.js:9:10492)
    at XMLHttpRequest.<anonymous> (https://ui5.sap.com/1.114.11/resources/sap/ushell_abap/bootstrap/evo/abap.js:9:10745)
    at o (https://ui5.sap.com/1.114.11/resources/sap/ushell_abap/thirdparty/sap-xhrlib-esm.js:5:3967)
    at r.dispatch (https://ui5.sap.com/1.114.11/resources/sap/ushell_abap/thirdparty/sap-xhrlib-esm.js:5:4619)
    at a.handleEvent (https://ui5.sap.com/1.114.11/resources/sap/ushell_abap/thirdparty/sap-xhrlib-esm.js:5:29547)
    at XMLHttpRequest.t [as _fnHandler] (https://ui5.sap.com/1.114.11/resources/sap/ushell_abap/thirdparty/sap-xhrlib-esm.js:5:29890)
    at a.send (https://ui5.sap.com/1.114.11/resources/sap/ushell_abap/thirdparty/sap-xhrlib-esm.js:5:32155)
    at window.XMLHttpRequest.<computed> [as send] (https://ui5.sap.com/1.114.11/resources/sap/ushell_abap/bootstrap/evo/abap.js:239:318)
    at Ae (https://ui5.sap.com/1.114.11/resources/sap/ushell_abap/bootstrap/evo/abap.js:9:10837)
    at Ie (https://ui5.sap.com/1.114.11/resources/sap/ushell_abap/bootstrap/evo/abap.js:9:14462)
```

### Spreadsheet Component Init

```js
"FinTransFlowTypeList": {
          "type": "Component",
          "id": "FinTransFlowTypeList",
          "name": "sap.fe.templates.ListReport",
          "options": {
            "settings": {
              "contextPath": "/FinTransFlowType",
              "variantManagement": "Page",
              "navigation": {
                "FinTransFlowType": {
                  "detail": {
                    "route": "FinTransFlowTypeObjectPage"
                  }
                }
              },
              "initialLoad": "Enabled",
              "content": {
                "header": {
                  "actions": {
                    "ListPageExtController": {
                      "press": "zfintransflowtype.zfintransflowtype.ext.listPageExtController.ListPageExtController.openSpreadsheetUploadDialog",
                      "visible": true,
                      "enabled": true,
                      "requiresSelection": false,
                      "text": "{@i18n>cargaExcel}"
                    }
                  }
                }
              }
            }
          }
        },
```

### Manifest

```json
"resourceRoots": {
      "cc.spreadsheetimporter.v0_31_1": "./thirdparty/customControl/spreadsheetImporter/v0_31_1"
    },
    "componentUsages": {
      "spreadsheetImporter": {
        "name": "cc.spreadsheetimporter.v0_31_1"
      }
    }
```

**Comment by marianfoo** [comment]
Hi @andresj6 
in what environment are you executing the app?
Seems like on a On-Premise Launchpad?

Did you execute all steps provided here?
https://docs.spreadsheet-importer.com/pages/GettingStarted/#setup-decentralized-deployment

Are you sure the component was deployed the abap system?
Can you have a look in the SE80 BSP App

**Comment by andresj6** [comment]
Hi Marian,

It seems that adjusting the dependencies with a quick fix or something like
that the "--all" was deleted from the build script.
It works now, thanks.

Best regards,

**Comment by marianfoo** [comment]
Happy to help!
